name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v2.4.0"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
